# ===================================================================
# JHipster Sample Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
  name: Dukang Registry config server
  status: Connected to the Dukang Registry config server, using https://github.com/eanfs/dukang-registry-sample-config.git !

dukang-workflow.fegin.name: dukang-workflow
workflow.fegin.name: martini
muscat.fegin.name: muscat
leave.fegin.name: dukang-leave
employee.fegin.name: dukang-employee-999998-900
dukang-cocktails.fegin.name: dukang-cocktails
drools.fegin.name: dukang-drools
grappa.fegin.name: grappa
claim.fegin.name: dukang-claim
erdinger.fegin.name: dukang-leave
tequila.fegin.name: dukang-user
authority.feign.name: dukang-authority
payroll.fegin.name: dukang-payroll
workforce.fegin.name: dukang-workforce
transfer.fegin.name: dukang-transfer

# Default JWT secret token (to be changed in production!)
jhipster:
  security:
    authentication:
      jwt:
        secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl

spring: 
  redis:
    database: 11
    host: workio-dev.redis.rds.aliyuncs.com
    port: 6379
    password: 1q2w%&$sdwQ2
  sleuth:
    sampler:
      percentage: 0.1  # 采样百分比，我这里配置了百分之百，

rabbitmq:
  host: rabbitmq
  port: 5672
  username: admin
  password: admin
  publisher-confirms: true
  virtual-host: /

management:
  security:
    enabled: false
